import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className="h-screen flex flex-col justify-between">
        <header className="bg-blue-600 p-4 text-white">
          <h1 className="text-2xl font-bold">My Marketing Product</h1>
        </header>
        <main className="flex-grow">
          {children}
        </main>
        <footer className="bg-blue-600 p-4 text-white text-center">
          &copy; 2025 My Company
        </footer>
      </body>
    </html>
  );
}
